/**
 * RawWoodResultViewer — Mode Ingénieur
 *
 * Affiche les résultats du moteur bois massif (raw_wood) avec :
 * - Visualisation SVG directe depuis {x, y, width, height}
 * - Tableau de contrôle par pièce (X, Y, rotation, alertes chevauchement)
 * - Alerte visuelle si une pièce dépasse la planche (dessinée en rouge)
 * - Bouton "Ouvrir le PDF de débit"
 * - Badge "Mode fallback Guillotine" si nécessaire
 */

import { useState, useMemo, memo, useId } from 'react';
import {
    AlertTriangle, CheckCircle2, ChevronDown, ChevronUp,
    ExternalLink, FileText, Maximize2, Minimize2, RotateCcw
} from 'lucide-react';

// ─── Types ──────────────────────────────────────────────────────────────────

interface RawPlacement {
    piece_id: number;
    piece_name: string;
    x: number;
    y: number;
    width: number;
    height: number;
    rotated: boolean;
    rotation_degrees: number;
    project_id?: number;
    project_name?: string;
    polygon_coords?: [number, number][];
}

interface RawPanel {
    panel_id: number;
    width: number;
    height: number;
    species?: string;
    waste_percentage?: number;
    placements: RawPlacement[];
    offcuts?: unknown[];
    polygon_coords?: [number, number][];
    defects?: [number, number][][];
}

interface RawWoodResult {
    success: boolean;
    panels_used: number;
    total_pieces: number;
    pieces_placed: number;
    pieces_remaining: number;
    waste_percentage: number;
    panels: RawPanel[];
    remaining_pieces?: { id: number; name: string }[];
    fallback_used?: boolean;
    algorithm?: string;
    optimizer_type?: string;
    metrics?: Record<string, number | string>;
    // Export paths (optional, generated by backend)
    export_paths?: {
        png?: string[];
        pdf?: string[];
    };
    export_files?: Record<string, string>;
}

interface RawWoodResultViewerProps {
    result: RawWoodResult;
    optimizationId?: number;
    onDownloadPack?: (format: string) => void;
}

// ─── Palette de couleurs pour les pièces ────────────────────────────────────

const PIECE_COLORS = [
    '#3B82F6', '#8B5CF6', '#10B981', '#F59E0B', '#EF4444',
    '#06B6D4', '#84CC16', '#F97316', '#EC4899', '#6366F1',
    '#14B8A6', '#A855F7', '#22C55E', '#EAB308', '#0EA5E9',
];

const getPieceColor = (index: number): string => PIECE_COLORS[index % PIECE_COLORS.length];

/** Résoudre le chemin backend en URL http */
const toExportUrl = (path: string): string => {
    if (!path) return '';
    // Nettoyage du chemin Windows/Linux et conversion en URL
    const clean = path.replace(/\\/g, '/');
    // Si le chemin contient déjà "exports/", on cible le bon endpoint
    const match = clean.match(/exports[\\/](.+)/);
    const exportPart = match ? match[1] : clean.replace(/^\/+/, '');
    return `http://localhost:8000/exports/${exportPart}`;
};

// ─── Vérification de chevauchement ──────────────────────────────────────────

interface OverlapInfo {
    a: string;
    b: string;
    overlapArea: number;
}

function detectOverlaps(placements: RawPlacement[]): OverlapInfo[] {
    const overlaps: OverlapInfo[] = [];
    for (let i = 0; i < placements.length; i++) {
        for (let j = i + 1; j < placements.length; j++) {
            const a = placements[i];
            const b = placements[j];
            const ix = Math.max(0, Math.min(a.x + a.width, b.x + b.width) - Math.max(a.x, b.x));
            const iy = Math.max(0, Math.min(a.y + a.height, b.y + b.height) - Math.max(a.y, b.y));
            const area = ix * iy;
            if (area > 1) {
                overlaps.push({ a: a.piece_name, b: b.piece_name, overlapArea: area });
            }
        }
    }
    return overlaps;
}

// ─── Composant SVG d'une planche ────────────────────────────────────────────

const BoardSVG = memo(function BoardSVG({
    panel,
    colorMap
}: {
    panel: RawPanel;
    colorMap: Map<number, string>;
}) {
    const [hoveredId, setHoveredId] = useState<number | null>(null);
    const reactId = useId();

    const padding = Math.max(panel.width, panel.height) * 0.04;
    const vb = `${-padding} ${-padding} ${panel.width + 2 * padding} ${panel.height + 2 * padding}`;

    // ID unique par instance de BoardSVG via useId()
    const patternId = `pattern-${reactId.replace(/:/g, '')}`;

    const gridStep = 100;
    const gridLines = [];
    for (let x = 0; x <= panel.width; x += gridStep) {
        gridLines.push(
            <line
                key={`vg-${x}-${reactId}`}
                x1={x}
                y1={0}
                x2={x}
                y2={panel.height}
                stroke="#e5e7eb"
                strokeWidth="0.5"
                strokeDasharray="6,4"
            />
        );
    }
    for (let y = 0; y <= panel.height; y += gridStep) {
        gridLines.push(
            <line
                key={`hg-${y}-${reactId}`}
                x1={0}
                y1={y}
                x2={panel.width}
                y2={y}
                stroke="#e5e7eb"
                strokeWidth="0.5"
                strokeDasharray="6,4"
            />
        );
    }

    return (
        <svg
            viewBox={vb}
            className="w-full h-auto border border-gray-200 dark:border-gray-700 rounded-lg bg-gray-50 dark:bg-gray-900/40"
        >
            {/* DEFS EN PREMIER avec ID unique */}
            <defs key={`${reactId}-defs`}>
                <pattern id={patternId} width="8" height="8" patternUnits="userSpaceOnUse">
                    <line x1="0" y1="8" x2="8" y2="0" stroke="#B91C1C" strokeWidth="1.5" />
                </pattern>
            </defs>

            {/* Grille */}
            {gridLines}

            {/* Contour planche */}
            {panel.polygon_coords && panel.polygon_coords.length >= 3 ? (
                <path
                    key={`${reactId}-board-poly`}
                    d={panel.polygon_coords.map((pt, i) => `${i === 0 ? 'M' : 'L'} ${pt[0]} ${pt[1]}`).join(' ') + ' Z'}
                    fill="rgba(146, 64, 14, 0.05)"
                    stroke="#92400e"
                    strokeWidth="3"
                />
            ) : (
                <rect key={`${reactId}-board-rect`} x={0} y={0} width={panel.width} height={panel.height}
                    fill="rgba(146, 64, 14, 0.05)" stroke="#92400e" strokeWidth="3" rx="2" />
            )}

            {/* Défauts */}
            {panel.defects?.map((defect, didx) => (
                <path
                    key={`defect-${panel.panel_id}-${didx}`}
                    d={defect.map((pt, i) => `${i === 0 ? 'M' : 'L'} ${pt[0]} ${pt[1]}`).join(' ') + ' Z'}
                    fill="#FEE2E2"
                    fillOpacity="0.6"
                    stroke="#EF4444"
                    strokeWidth="1.5"
                    strokeDasharray="4,2"
                />
            ))}

            {/* Repères de dimensions */}
            <text key={`${reactId}-dim-w`} x={panel.width / 2} y={-padding * 0.4} textAnchor="middle"
                fill="#92400e" fontSize={padding * 0.9} fontFamily="monospace">
                {panel.width} mm
            </text>
            <text key={`${reactId}-dim-h`} x={-padding * 0.35} y={panel.height / 2} textAnchor="middle"
                fill="#92400e" fontSize={padding * 0.9} fontFamily="monospace"
                transform={`rotate(-90, ${-padding * 0.35}, ${panel.height / 2})`}>
                {panel.height} mm
            </text>

            {/* Pièces */}
            {panel.placements.map((plc, idx) => {
                const isOutside = (
                    plc.x < 0 || plc.y < 0 ||
                    plc.x + plc.width > panel.width ||
                    plc.y + plc.height > panel.height
                );
                const hovered = hoveredId === plc.piece_id;
                const color = isOutside ? '#EF4444' : (colorMap.get(plc.piece_id) || getPieceColor(idx));

                // Priorité : polygon_coords > fallback rect
                let pathD = '';
                if (plc.polygon_coords && plc.polygon_coords.length >= 3) {
                    pathD = plc.polygon_coords
                        .map((pt, i) => `${i === 0 ? 'M' : 'L'} ${pt[0]} ${pt[1]}`)
                        .join(' ') + ' Z';
                }

                const cx = plc.x + plc.width / 2;
                const cy = plc.y + plc.height / 2;

                return (
                    <g key={`p-${plc.piece_id}-${idx}-${plc.x}-${plc.y}`}
                        onMouseEnter={() => setHoveredId(plc.piece_id)}
                        onMouseLeave={() => setHoveredId(null)}
                        className="cursor-pointer"
                    >
                        {/* Fond de la pièce */}
                        {pathD ? (
                            <path
                                key={`path-bg-${plc.piece_id}-${idx}`}
                                d={pathD}
                                fill={color} fillOpacity={hovered ? 0.85 : 0.65}
                                stroke={isOutside ? '#B91C1C' : (hovered ? '#1E40AF' : '#374151')}
                                strokeWidth={hovered ? 3 : 1.5}
                            />
                        ) : (
                            <rect
                                key={`rect-bg-${plc.piece_id}-${idx}`}
                                x={plc.x} y={plc.y} width={plc.width} height={plc.height}
                                fill={color} fillOpacity={hovered ? 0.85 : 0.65}
                                stroke={isOutside ? '#B91C1C' : (hovered ? '#1E40AF' : '#374151')}
                                strokeWidth={hovered ? 3 : 1.5}
                                rx="2"
                            />
                        )}

                        {/* Hachures si hors planche */}
                        {isOutside && (
                            <rect
                                key={`overlap-p-${plc.piece_id}-${idx}`}
                                x={plc.x} y={plc.y} width={plc.width} height={plc.height}
                                fill={`url(#${patternId})`} fillOpacity="0.3"
                                stroke="none"
                            />
                        )}

                        {/* Label pièce */}
                        <text
                            key={`label-p-${plc.piece_id}-${idx}`}
                            x={cx} y={cy - 4} textAnchor="middle" dominantBaseline="middle"
                            fill="#FFFFFF" fontSize={Math.min(plc.width, plc.height) * 0.12}
                            fontWeight="bold" fontFamily="sans-serif"
                            className="pointer-events-none select-none"
                            style={{ textShadow: '0 1px 3px rgba(0,0,0,0.7)' }}
                        >
                            {plc.piece_name.length > 14 ? plc.piece_name.slice(0, 12) + '…' : plc.piece_name}
                        </text>
                        <text
                            key={`dim-p-${plc.piece_id}-${idx}`}
                            x={cx} y={cy + Math.min(plc.width, plc.height) * 0.09} textAnchor="middle"
                            fill="rgba(255,255,255,0.75)" fontSize={Math.min(plc.width, plc.height) * 0.09}
                            fontFamily="monospace" className="pointer-events-none select-none"
                        >
                            {plc.width.toFixed(0)}×{plc.height.toFixed(0)}
                        </text>

                        {/* Icône rotation */}
                        {plc.rotation_degrees !== 0 && (
                            <text
                                key={`rot-p-${plc.piece_id}-${idx}`}
                                x={plc.x + 6} y={plc.y + 12}
                                fill="white" fontSize="9" opacity="0.8"
                                className="pointer-events-none select-none"
                            >
                                ↺{plc.rotation_degrees.toFixed(0)}°
                            </text>
                        )}

                        {/* Icône alerte hors-planche */}
                        {isOutside && (
                            <text
                                key={`alert-p-${plc.piece_id}-${idx}`}
                                x={cx} y={plc.y + 14} textAnchor="middle"
                                fill="#FFF" fontSize="11" fontWeight="bold"
                                className="pointer-events-none select-none"
                            >
                                ⚠ HORS PLANCHE
                            </text>
                        )}

                        <title>
                            {`${plc.piece_name}\nX: ${plc.x.toFixed(1)} mm, Y: ${plc.y.toFixed(1)} mm\n${plc.width.toFixed(1)} × ${plc.height.toFixed(1)} mm\nRotation: ${plc.rotation_degrees.toFixed(0)}°${isOutside ? '\n⚠️ HORS LIMITE!' : ''}`}
                        </title>
                    </g>
                );
            })}
        </svg>
    );
});

// ─── Tableau de contrôle des pièces ─────────────────────────────────────────

const PlacementControlTable = memo(function PlacementControlTable({
    panel,
    overlaps
}: {
    panel: RawPanel;
    overlaps: OverlapInfo[];
}) {
    const overlapSet = new Set(overlaps.flatMap(o => [o.a, o.b]));

    return (
        <div className="mt-4 overflow-x-auto rounded-lg border border-gray-200 dark:border-gray-700">
            <table className="w-full text-xs font-mono">
                <thead>
                    <tr className="bg-gray-50 dark:bg-gray-800 text-gray-500 dark:text-gray-400 uppercase text-[10px] tracking-wider">
                        <th className="text-left py-2 px-3">Pièce</th>
                        <th className="text-right py-2 px-3">X (mm)</th>
                        <th className="text-right py-2 px-3">Y (mm)</th>
                        <th className="text-right py-2 px-3">L × H (mm)</th>
                        <th className="text-right py-2 px-3">Rotation</th>
                        <th className="text-center py-2 px-3">Statut</th>
                    </tr>
                </thead>
                <tbody>
                    {panel.placements.map((plc, idx) => {
                        const isOutside = (
                            plc.x < 0 || plc.y < 0 ||
                            plc.x + plc.width > panel.width ||
                            plc.y + plc.height > panel.height
                        );
                        const hasOverlap = overlapSet.has(plc.piece_name);
                        const hasIssue = isOutside || hasOverlap;

                        return (
                            <tr key={`row-${plc.piece_id}-${idx}-${plc.x}-${plc.y}`}
                                className={`border-t border-gray-100 dark:border-gray-800 transition-colors ${hasIssue
                                    ? 'bg-red-50/80 dark:bg-red-900/15'
                                    : 'hover:bg-gray-50 dark:hover:bg-gray-800/50'
                                    }`}
                            >
                                <td className="py-2 px-3 font-semibold text-gray-800 dark:text-gray-200">
                                    {plc.piece_name}
                                </td>
                                <td className="py-2 px-3 text-right tabular-nums text-gray-600 dark:text-gray-400">
                                    {plc.x.toFixed(1)}
                                </td>
                                <td className="py-2 px-3 text-right tabular-nums text-gray-600 dark:text-gray-400">
                                    {plc.y.toFixed(1)}
                                </td>
                                <td className="py-2 px-3 text-right tabular-nums text-gray-600 dark:text-gray-400">
                                    {plc.width.toFixed(0)} × {plc.height.toFixed(0)}
                                </td>
                                <td className="py-2 px-3 text-right text-gray-500 dark:text-gray-500">
                                    {plc.rotation_degrees !== 0 ? (
                                        <span className="flex items-center justify-end gap-1">
                                            <RotateCcw className="w-3 h-3" />
                                            {plc.rotation_degrees.toFixed(0)}°
                                        </span>
                                    ) : '—'}
                                </td>
                                <td className="py-2 px-3 text-center">
                                    {hasIssue ? (
                                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 text-[10px] font-bold uppercase">
                                            <AlertTriangle className="w-3 h-3" />
                                            {isOutside ? 'Hors limite' : 'Chevauchement'}
                                        </span>
                                    ) : (
                                        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 text-[10px] font-bold uppercase">
                                            <CheckCircle2 className="w-3 h-3" />
                                            OK
                                        </span>
                                    )}
                                </td>
                            </tr>
                        );
                    })}
                </tbody>
            </table>

            {/* Résumé chevauchements */}
            {overlaps.length > 0 && (
                <div className="p-3 bg-red-50 dark:bg-red-900/20 border-t border-red-100 dark:border-red-800">
                    <p className="text-xs font-bold text-red-700 dark:text-red-400 mb-2 flex items-center gap-1">
                        <AlertTriangle className="w-3 h-3" />
                        {overlaps.length} chevauchement{overlaps.length > 1 ? 's' : ''} détecté{overlaps.length > 1 ? 's' : ''} :
                    </p>
                    {overlaps.map((o, i) => (
                        <p key={`overlap-item-${panel.panel_id}-${i}`} className="text-xs text-red-600 dark:text-red-400 font-mono pl-4">
                            → {o.a} ↔ {o.b} ({o.overlapArea.toFixed(0)} mm²)
                        </p>
                    ))}
                </div>
            )}
        </div>
    );
});

// ─── Composant principal ─────────────────────────────────────────────────────

export function RawWoodResultViewer({
    result: inputResult,
    optimizationId,
    onDownloadPack
}: RawWoodResultViewerProps) {
    console.log('[RawWoodResultViewer] Rendering with inputResult:', inputResult);
    const [fullscreenPanelIdx, setFullscreenPanelIdx] = useState<number | null>(null);
    const [showTableFor, setShowTableFor] = useState<Set<number>>(new Set());

    // ── Trust pre-normalized result from caller ──
    const result = useMemo(() => {
        if (!inputResult) return null as unknown as RawWoodResult;
        return {
            ...inputResult,
            panels: inputResult.panels || [],
            optimizer_type: inputResult.optimizer_type || 'raw_wood'
        };
    }, [inputResult]);
    // ──────────────────────────────────────────────
    // ─────────────────────────────────────────────────────────────────────────────

    // Palette de couleurs stable par piece_id
    const colorMap = useMemo(() => {
        const map = new Map<number, string>();
        if (!result || !result.panels) {
            console.warn('[RawWoodResultViewer] No result or panels for colorMap');
            return map;
        }
        let colorIdx = 0;
        result.panels.forEach(panel => {
            if (!panel.placements) return;
            panel.placements.forEach((plc: any) => {
                if (plc && plc.piece_id !== undefined && !map.has(plc.piece_id)) {
                    map.set(plc.piece_id, getPieceColor(colorIdx++));
                }
            });
        });
        return map;
    }, [result]);

    // URLs PDF (Recherche de la clé finissant par "pdf" ou contenant pdf dans le nom)
    let pdfPathData = null;
    if (result.export_files) {
        // Chercher une clé contenant pdf (ex: 'pdf', 'BATCH_1_Projets.pdf')
        const pdfKey = Object.keys(result.export_files).find(k => {
            const val = result.export_files![k];
            return k.toLowerCase().includes('pdf') || (typeof val === 'string' && val.toLowerCase().endsWith('.pdf'));
        });
        if (pdfKey) {
            pdfPathData = result.export_files[pdfKey];
        }
    }

    // Fallback à OptimizationId sinon
    const pdfUrl = pdfPathData
        ? toExportUrl(pdfPathData)
        : optimizationId
            ? `http://localhost:8000/exports/optimization_${optimizationId}.pdf`
            : null;

    const toggleTable = (idx: number) => {
        setShowTableFor(prev => {
            const next = new Set(prev);
            if (next.has(idx)) next.delete(idx);
            else next.add(idx);
            return next;
        });
    };

    if (!result || !result.panels) {
        console.error('[RawWoodResultViewer] CRITICAL: No result or panels available for rendering');
        return (
            <div className="p-8 text-center bg-red-50 dark:bg-red-900/10 border border-dashed border-red-200 dark:border-red-900/30 rounded-2xl">
                <p className="text-red-600 dark:text-red-400 font-medium">Erreur d'affichage : Données de résultat non valides.</p>
                <p className="text-xs text-red-500 dark:text-red-500/70 mt-2">Veuillez consulter la console pour plus de détails.</p>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* ── En-tête résumé ── */}
            <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-gradient-to-r from-emerald-50 to-teal-50 dark:from-emerald-900/20 dark:to-teal-900/20 rounded-xl border border-emerald-100 dark:border-emerald-900/30">
                <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full bg-emerald-100 dark:bg-emerald-900/40 flex items-center justify-center">
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    <div>
                        <h3 className="font-bold text-gray-900 dark:text-white text-base">
                            {result.pieces_placed}/{result.total_pieces} pièces placées
                        </h3>
                        <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                            {result.panels_used} planche{result.panels_used > 1 ? 's' : ''} utilisée{result.panels_used > 1 ? 's' : ''}
                            {' · '}
                            {result.waste_percentage?.toFixed(1) ?? '—'} % de chutes
                            {result.fallback_used && (
                                <span className="ml-2 px-2 py-0.5 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-[10px] font-bold uppercase rounded border border-amber-200 dark:border-amber-800 animate-pulse">
                                    Mode Guillotine (Sans C++)
                                </span>
                            )}
                        </p>
                    </div>
                </div>

                {/* Boutons d'action */}
                <div className="flex flex-wrap gap-2">
                    {pdfUrl && (
                        <a
                            href={pdfUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center gap-2 px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white rounded-lg text-sm font-semibold transition-colors shadow-sm"
                        >
                            <FileText className="w-4 h-4" />
                            Ouvrir le PDF de débit
                            <ExternalLink className="w-3 h-3 opacity-75" />
                        </a>
                    )}
                    <button
                        type="button"
                        onClick={() => onDownloadPack?.('pdf')}
                        className="flex items-center gap-2 px-3 py-2 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg text-sm transition-colors"
                    >
                        <FileText className="w-4 h-4" />
                        Pack PDF
                    </button>
                    <button
                        type="button"
                        onClick={() => onDownloadPack?.('dxf')}
                        className="flex items-center gap-2 px-3 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm transition-colors"
                    >
                        Export DXF
                    </button>
                </div>
            </div>

            {/* ── Pièces non-placées ── */}
            {result.remaining_pieces && result.remaining_pieces.length > 0 && (
                <div className="p-4 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-900/30 rounded-xl">
                    <p className="text-sm font-bold text-amber-800 dark:text-amber-300 flex items-center gap-2 mb-2">
                        <AlertTriangle className="w-4 h-4" />
                        {result.remaining_pieces.length} pièce{result.remaining_pieces.length > 1 ? 's' : ''} non-placée{result.remaining_pieces.length > 1 ? 's' : ''} :
                    </p>
                    <div className="flex flex-wrap gap-2">
                        {result.remaining_pieces.map(p => (
                            <span key={p.id} className="px-2 py-1 bg-amber-100 dark:bg-amber-900/40 text-amber-800 dark:text-amber-300 rounded text-xs font-mono">
                                {p.name || `Pièce #${p.id}`}
                            </span>
                        ))}
                    </div>
                </div>
            )}

            {/* ── Planches ── */}
            {result.panels.length === 0 ? (
                <div className="p-8 text-center bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-dashed border-gray-300 dark:border-gray-700">
                    <AlertTriangle className="w-10 h-10 text-amber-500 mx-auto mb-3" />
                    <p className="text-gray-600 dark:text-gray-400">Aucune planche générée.</p>
                </div>
            ) : (
                result.panels.map((panel, idx) => {
                    const overlaps = detectOverlaps(panel.placements);
                    const hasIssues = overlaps.length > 0 ||
                        panel.placements.some(p =>
                            p.x < 0 || p.y < 0 ||
                            p.x + p.width > panel.width ||
                            p.y + p.height > panel.height
                        );
                    const isFs = fullscreenPanelIdx === idx;
                    const tableShown = showTableFor.has(idx);
                    const efficiency = panel.waste_percentage !== undefined
                        ? (100 - panel.waste_percentage).toFixed(1)
                        : '—';

                    return (
                        <div
                            key={`board-container-${panel.panel_id}-${idx}`}
                            className={`rounded-xl border shadow-sm transition-all p-5 ${hasIssues
                                ? 'border-red-200 dark:border-red-900/40 bg-red-50/30 dark:bg-red-900/5'
                                : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800/40'
                                }`}
                        >
                            {/* En-tête planche */}
                            <div className="flex items-center justify-between mb-4">
                                <div>
                                    <h4 className="font-bold text-gray-800 dark:text-white text-sm flex items-center gap-2">
                                        Planche #{idx + 1}
                                        {panel.species && (
                                            <span className="px-2 py-0.5 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-[10px] font-bold uppercase rounded">
                                                {panel.species}
                                            </span>
                                        )}
                                        {hasIssues && (
                                            <span className="px-2 py-0.5 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 text-[10px] font-bold uppercase rounded flex items-center gap-1">
                                                <AlertTriangle className="w-3 h-3" /> Anomalie
                                            </span>
                                        )}
                                    </h4>
                                    <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                                        {panel.width} × {panel.height} mm
                                        {' · '}{panel.placements.length} pièce{panel.placements.length > 1 ? 's' : ''}
                                        {' · '}Remplissage : <strong>{efficiency}%</strong>
                                    </p>
                                </div>
                                <div className="flex items-center gap-2">
                                    {/* Toggle tableau de contrôle */}
                                    <button
                                        type="button"
                                        onClick={() => toggleTable(idx)}
                                        className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-colors ${tableShown
                                            ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400'
                                            : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700'
                                            }`}
                                    >
                                        {tableShown ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                                        Contrôle
                                        {hasIssues && <span className="ml-1 w-2 h-2 rounded-full bg-red-500 animate-pulse" />}
                                    </button>
                                    {/* Plein écran */}
                                    <button
                                        type="button"
                                        onClick={() => setFullscreenPanelIdx(isFs ? null : idx)}
                                        className="p-1.5 rounded-lg bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
                                        title={isFs ? 'Réduire' : 'Plein écran'}
                                    >
                                        <Maximize2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>

                            {/* SVG planche */}
                            <BoardSVG key={`board-${panel.panel_id}-${idx}`} panel={panel} colorMap={colorMap} />

                            {/* Tableau de contrôle (dépliable) */}
                            {tableShown && (
                                <PlacementControlTable panel={panel} overlaps={overlaps} />
                            )}

                            {/* Légende */}
                            <div className="mt-3 flex flex-wrap gap-4 text-xs text-gray-500 dark:text-gray-400">
                                <div className="flex items-center gap-2">
                                    <div className="w-4 h-4 bg-blue-500 opacity-65 rounded" />
                                    <span>Pièces placées</span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <div className="w-4 h-4 bg-red-500 opacity-65 rounded" />
                                    <span>Hors limite</span>
                                </div>
                                <div className="flex items-center gap-2 ml-auto">
                                    <span className="font-mono">Grille: 100 mm</span>
                                </div>
                            </div>
                        </div>
                    );
                })
            )}

            {/* ── MODAL PLEIN ÉCRAN (Déplacé hors de la boucle pour stabilité DOM) ── */}
            {fullscreenPanelIdx !== null && result.panels[fullscreenPanelIdx] && (
                <div
                    key="fullscreen-modal-root"
                    className="fixed inset-0 z-[9999] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"
                    onClick={() => setFullscreenPanelIdx(null)}
                >
                    <div
                        className="bg-white dark:bg-gray-900 rounded-2xl p-6 max-w-7xl w-full max-h-[95vh] overflow-auto shadow-2xl border border-gray-200 dark:border-gray-700"
                        onClick={e => e.stopPropagation()}
                    >
                        <div className="flex justify-between items-center mb-6">
                            <div>
                                <h4 className="font-bold text-gray-900 dark:text-white text-xl">
                                    Planche #{fullscreenPanelIdx + 1}
                                    {result.panels[fullscreenPanelIdx].species && (
                                        <span className="ml-3 px-3 py-1 bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-400 text-xs font-bold uppercase rounded-full">
                                            {result.panels[fullscreenPanelIdx].species}
                                        </span>
                                    )}
                                </h4>
                                <p className="text-sm text-gray-500 mt-1">
                                    {result.panels[fullscreenPanelIdx].width} × {result.panels[fullscreenPanelIdx].height} mm
                                </p>
                            </div>
                            <button
                                type="button"
                                onClick={() => setFullscreenPanelIdx(null)}
                                className="p-3 rounded-full bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 transition-all shadow-sm"
                            >
                                <Minimize2 className="w-6 h-6 text-gray-600 dark:text-gray-300" />
                            </button>
                        </div>
                        <div className="bg-gray-50 dark:bg-gray-950 p-4 rounded-xl border border-gray-200 dark:border-gray-800">
                            <BoardSVG panel={result.panels[fullscreenPanelIdx]} colorMap={colorMap} />
                        </div>
                    </div>
                </div>
            )}

            {/* ── Métriques techniques (Mode Ingénieur) ── */}
            {result.metrics && Object.keys(result.metrics).length > 0 && (
                <details className="group">
                    <summary className="flex items-center gap-2 text-xs font-semibold text-gray-500 dark:text-gray-500 uppercase tracking-wider cursor-pointer hover:text-gray-700 dark:hover:text-gray-300 list-none py-2 select-none">
                        <ChevronDown className="w-4 h-4 group-open:rotate-180 transition-transform" />
                        Métriques Techniques (Mode Ingénieur)
                    </summary>
                    <div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-3">
                        {Object.entries(result.metrics).map(([k, v]) => (
                            <div key={k} className="bg-gray-50 dark:bg-gray-800/60 rounded-lg p-3 border border-gray-100 dark:border-gray-700">
                                <div className="text-[10px] font-bold text-gray-400 dark:text-gray-500 uppercase tracking-wide mb-1">
                                    {k.replace(/_/g, ' ')}
                                </div>
                                <div className="text-sm font-mono font-bold text-gray-800 dark:text-gray-200 truncate">
                                    {typeof v === 'number' ? v.toFixed(typeof v === 'number' && v < 1 ? 4 : 1) : String(v)}
                                </div>
                            </div>
                        ))}
                    </div>
                </details>
            )}
        </div>
    );
}
