import { ColorPalette } from '../context/ThemeContext';

export interface ThemePreset {
    id: string;
    name: string;
    description: string;
    category: 'built-in' | 'custom';
    light: ColorPalette;
    dark: ColorPalette;
    createdAt?: string;
    tags?: string[];
}

export const BUILT_IN_PRESETS: ThemePreset[] = [
    {
        id: 'default',
        name: 'Défaut',
        description: 'Palette par défaut OptiCut',
        category: 'built-in',
        light: {
            primary: '#3b82f6',
            secondary: '#8b5cf6',
            accent: '#ec4899',
            background: '#f8fafc',
            surface: '#ffffff',
            text: '#1e293b',
            border: '#e2e8f0',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
        },
        dark: {
            primary: '#60a5fa',
            secondary: '#a78bfa',
            accent: '#f472b6',
            background: '#0f172a',
            surface: '#1e293b',
            text: '#f1f5f9',
            border: '#334155',
            success: '#34d399',
            warning: '#fbbf24',
            error: '#f87171',
        },
        tags: ['bleu', 'professionnel']
    },
    {
        id: 'ocean',
        name: 'Océan',
        description: 'Palette bleue marine et apaisante',
        category: 'built-in',
        light: {
            primary: '#0369a1',
            secondary: '#06b6d4',
            accent: '#0891b2',
            background: '#f0f9ff',
            surface: '#ffffff',
            text: '#082f49',
            border: '#bae6fd',
            success: '#06b6d4',
            warning: '#ea580c',
            error: '#dc2626',
        },
        dark: {
            primary: '#0ea5e9',
            secondary: '#22d3ee',
            accent: '#06b6d4',
            background: '#001a33',
            surface: '#003d66',
            text: '#e0f2fe',
            border: '#0369a1',
            success: '#22d3ee',
            warning: '#fb923c',
            error: '#f87171',
        },
        tags: ['océan', 'bleu', 'calme']
    },
    {
        id: 'sunset',
        name: 'Coucher de soleil',
        description: 'Palette chaude avec oranges et rouges',
        category: 'built-in',
        light: {
            primary: '#ea580c',
            secondary: '#f97316',
            accent: '#fb923c',
            background: '#fef3c7',
            surface: '#ffffff',
            text: '#7c2d12',
            border: '#fed7aa',
            success: '#84cc16',
            warning: '#f59e0b',
            error: '#dc2626',
        },
        dark: {
            primary: '#f97316',
            secondary: '#fb923c',
            accent: '#fbbf24',
            background: '#331401',
            surface: '#662d05',
            text: '#fef3c7',
            border: '#ea580c',
            success: '#a3e635',
            warning: '#fbbf24',
            error: '#f87171',
        },
        tags: ['chaud', 'orange', 'créatif']
    },
    {
        id: 'forest',
        name: 'Forêt',
        description: 'Palette verte naturelle et relaxante',
        category: 'built-in',
        light: {
            primary: '#15803d',
            secondary: '#16a34a',
            accent: '#22c55e',
            background: '#f0fdf4',
            surface: '#ffffff',
            text: '#15550f',
            border: '#bbf7d0',
            success: '#16a34a',
            warning: '#ca8a04',
            error: '#dc2626',
        },
        dark: {
            primary: '#22c55e',
            secondary: '#4ade80',
            accent: '#86efac',
            background: '#051a0f',
            surface: '#0d3b1f',
            text: '#dcfce7',
            border: '#15803d',
            success: '#4ade80',
            warning: '#eab308',
            error: '#f87171',
        },
        tags: ['vert', 'nature', 'écologique']
    },
    {
        id: 'purple',
        name: 'Violet mystique',
        description: 'Palette violette élégante et moderne',
        category: 'built-in',
        light: {
            primary: '#7c3aed',
            secondary: '#a855f7',
            accent: '#d946ef',
            background: '#faf5ff',
            surface: '#ffffff',
            text: '#4c1d95',
            border: '#e9d5ff',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#dc2626',
        },
        dark: {
            primary: '#a855f7',
            secondary: '#d946ef',
            accent: '#f0abfc',
            background: '#2e1065',
            surface: '#5b21b6',
            text: '#f3e8ff',
            border: '#7c3aed',
            success: '#34d399',
            warning: '#fbbf24',
            error: '#f87171',
        },
        tags: ['violet', 'moderne', 'premium']
    },
    {
        id: 'minimal',
        name: 'Minimaliste',
        description: 'Palette épurée noir et blanc',
        category: 'built-in',
        light: {
            primary: '#000000',
            secondary: '#404040',
            accent: '#1f2937',
            background: '#ffffff',
            surface: '#f9fafb',
            text: '#000000',
            border: '#e5e7eb',
            success: '#047857',
            warning: '#d97706',
            error: '#991b1b',
        },
        dark: {
            primary: '#ffffff',
            secondary: '#d1d5db',
            accent: '#9ca3af',
            background: '#111827',
            surface: '#1f2937',
            text: '#f9fafb',
            border: '#4b5563',
            success: '#6ee7b7',
            warning: '#fcd34d',
            error: '#fca5a5',
        },
        tags: ['minimaliste', 'classique', 'épuré']
    },
    {
        id: 'neon',
        name: 'Néon futuriste',
        description: 'Palette vibrant avec couleurs néon',
        category: 'built-in',
        light: {
            primary: '#00d9ff',
            secondary: '#ff006e',
            accent: '#ffbe0b',
            background: '#fafafa',
            surface: '#ffffff',
            text: '#333333',
            border: '#e0e0e0',
            success: '#00ff00',
            warning: '#ffbe0b',
            error: '#ff0055',
        },
        dark: {
            primary: '#00d9ff',
            secondary: '#ff006e',
            accent: '#ffbe0b',
            background: '#0a0a0a',
            surface: '#1a1a1a',
            text: '#ffffff',
            border: '#333333',
            success: '#00ff00',
            warning: '#ffbe0b',
            error: '#ff0055',
        },
        tags: ['néon', 'futuriste', 'vibrant']
    },
];
